version: '3.7'

services:

  postgres:
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=movies
    ports:
      - 5432:5432
    volumes:
      - movies_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.2-alpine
    ports:
      - 6379:6379

volumes:
  movies_data: